services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: kg_api
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    restart: unless-stopped

  neo4j:
    image: neo4j:5.20
    container_name: kg_neo4j
    environment:
      - NEO4J_AUTH=none              # pour l'instant pas d'authentification
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
    ports:
      - "7474:7474"  # UI
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
